### ISSUE TITLE
Bcrypt package not a valid win32 application

### ISSUE THREAD

**Issue by Johnmiicheal** [Johnmiicheal/re-notify#1]
`bcrypt\lib\binding\napi-v3\bcrypt_lib.node is not a valid Win32 application.`

This is the issue currently
@owolabioromidayo

**Comment by owolabioromidayo** [comment]
What is your dev env? WSL or Windows?

**Comment by owolabioromidayo** [comment]
You really shouldn't use windows.

**Comment by Johnmiicheal** [comment]
> What is your dev env? WSL or Windows?

I used wsl to install the package. my express server is running on windows

**Comment by Johnmiicheal** [comment]
I'm reinstalling bcrypt on windows

**Comment by owolabioromidayo** [comment]
Just do everything in one place. Put your express server in WSL.
